Repository ivanilves/lstags, pull requests merged in 2018-05, with the labels that each got.

#151 Add sample development environment initialization
  Makefile
  README.md
  api/registry/registry_test.go
  api_usage.go.sample
Labels: chore, documentation

#152 Update comments for GoDoc
  api/internal/registry/registry.go
  api/internal/registry/registry_test.go
  api/v1/collection/collection.go
  api/v1/collection/collection_test.go
  api/v1/v1.go
  api/v1/v1_test.go
  repository/repository.go
  tag/tag.go
Labels: documentation, enhancement

#159 chore(CI): MacOSX-friendly scripts
  Makefile
Labels: chore
