Repository ivanilves/lstags, pull requests merged in 2018-04, with the labels that each got.

#135 FEATURE: Daemon mode [ISSUE-133]
  main.go
Labels: feature

#141 NORELEASE: Document `--push-prefix` feature behavior
  README.md
Labels: documentation

#147 IMPROVE: Tolerate errors on `Pull` and `Push` actions
  api/v1/v1.go
  main.go
  util/wait/wait.go
Labels: bugfix, enhancement

#150 NORELEASE: To fail or not to fail?
  README.md
Labels: documentation
